import Head from "next/head";
import Navbar from "../Components/Navbar/Navbar";
import Home1 from "../Components/Home1/Home1";
import styles from "../styles/Home.module.css";
import About from "../Components/About/About";
import Contact from "../Components/Contact/Contact";
import Projects from "../Components/Projects/Projects";
import App from "../Components/Swiper/App";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kim Ngan Le - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home1 />
      <Projects />
      <App />
      <About />
      <Contact />
      <footer className={styles.footer}>© Copyright ChiranjitH.com</footer>
    </div>
  );
}
